### PR TITLE
Some shiny new colour codes for all messages

### PR DESCRIPTION
**Pull request by EvilOlaf**
Did not test these messages yet. We need some public feedback :D.

As a side node:
There could be a customizable prefix attached to all messages like "[BanManager]". Either by adding a new language string in the `messages.yml` to have all prefixes edited by once or just let the users add their custom prefixes to each string by hand.

### CODE REVIEW

**Comment by confuser** [comment]
:+1: I'll merge in a few days

As for prefix, not a fan. I find that they often take up valuable onscreen space for little to no reason.

**Comment by EvilOlaf** [comment]
We both think practical ;) But some kids like this stuff and even more like it when more than the half chat line is wasted for prefixes and useless stuff :P

**Comment by Kakifrucht** [comment]
Prefixes are not useless at all. They provide a nice structure to the chat imo. I personally added a prefix to every single message in the translation file.

**Comment by EvilOlaf** [comment]
Did you forget this one? :P

**Comment by confuser** [comment]
Apologies, it appears so. Can you rebase this and I'll get it merged into a
patch release.

**Comment by EvilOlaf** [comment]
Will need a few days as  I am currently on vacation.

**Comment by EvilOlaf** [comment]
Hope I did not miss anything: https://github.com/EvilOlaf/BanManager/blob/master/src/main/resources/messages.yml

**Pull request closed without merging**
