### PR TITLE
Change build process to gradle

### PR DESCRIPTION
**Pull request by JOO200**
As discussed on the discord here is the Pull Request for the gradle setup.

I'm opening it as a draft as some thing are not ready yes. You can compile that plugin already but there might be unknown issues.

### Changes:

- The gradle setup is heavily inspired by [WorldGuard](https://github.com/EngineHub/WorldGuard/) and [WorldEdit](https://github.com/EngineHub/WorldEdit/).
- Use build.gradle.kts files to configure building
- Relocate the libraries before usage in BanManagerCommon (or the other subprojects)
  - you can now publish BanManagerCommon and BanManagerLibs as maven artifacts and other peope don't need to depend on the plugin code. (other plugin authors can use the Common Module for platform unrelated code or include the Common Module in their own plugin)
  - therfore changed many imports in Common Module
- Removed slf4j (doesn't look like something is missing this)

### ToDos:

- [x] Fix the Tests (missing configuration files from resources folder)
- [x] Check for correct Sponge version / fix Sponge plugin
- [x] test the important stuff on every platform
- [x] setup/fix maven publishing task
- [x] setup/fix github actions / ci
- [x] broken api changes by package relocations
- [x] add org.gradle.parallel=true to gradle.properties to speed up build

### CODE REVIEW

**Comment by JOO200** [comment]
I convert it to a pr as it looks fine and it loaded on my paper and bungeecord test server.

Would like to have some feedback on the sponge implementation.

**Comment by A248** [comment]
> Removed slf4j (doesn't look like something is missing this)

HikariCP uses slf4j. You may end up shading slf4j since it will appear in the dependency graph. So, I'd suggest you relocate it too (in libs/build.gradle.kts, just as the other libraries are relocated)

**Comment by A248** [comment]
> therfore changed many imports in Common Module

Normally, you shouldn't need to change imports in the source code in order to relocate libraries. Usually, relocation is performed on end-user binaries, rather than intermediate artifacts.

I'm curious why you chose to create a "libs" artifact, and depend on that, rather than relocate your plugin jars and leave your source code untouched. Wouldn't you prefer to relocate at compile-time rather than changing imports?

**Comment by JOO200** [comment]
> HikariCP uses slf4j. You may end up shading slf4j since it will appear in the dependency graph. So, I'd suggest you relocate it too (in libs/build.gradle.kts, just as the other libraries are relocated)

This should be checked. We should check for that based on the platform.

> I'm curious why you chose to create a "libs" artifact, and depend on that, rather than relocate your plugin jars and leave your source code untouched. Wouldn't you prefer to relocate at compile-time rather than changing imports?

Not in this case. Yes, a "libs" artifact is weird but you may want to use the Core implementation in some other projects.
E.g. I want to have a Core Library accessing BanManager. With relocated stuff in the plugin stage I'm not able to import the Common/Core Module of this project as some classes are relocated in the plugin sources.

I know it's not the perfect solution but I don't think there is a good alternative unless you create an api module instead.

**Pull request merged**
