### PR TITLE
Velocity PR

### PR DESCRIPTION
**Pull request by Lorias-Jak**
Here is a great approach already started by my predecessor. I have already changed some things that were questionable for the license, as far as I have seen and found. Here once the PR I mean.
https://github.com/BanManagement/BanManager/pull/954

I unfortunately had to delete the whole mute-command structures, because velocity doesn't allow to prevent the chat-event since the signed chatmessages update of the 1.19. The whole thing must regulate the individual servers themselves. This can be done by installing banmanager on the subservers and connecting the database. Other implementations would be too complicated from my point of view. However, if it is desired differently, I can look with my limited knowledge something to work out, completely to the emergency must be resorted to Plugin messaging, whereby this causes further classes and the code more unclearly, because it would be necessary only for Velocity at the present time. 

I have not looked at all parts of the code carefully. If there are comments, feel free to let me know and mark the spots. I have tested everything that is known to me, so everything should work.
In case of need I am also reachable via Discord, there I will answer faster, because I see it faster.

### CODE REVIEW

**Comment by confuser** [comment]
Thank you for this @Lorias-Jak. Overall the PR looks great! 

Question on the muting issues, can you provide more docs on this? It looks like Velocity has it as an event? https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/player/PlayerChatEvent.html

I think we should still leverage it to enable muting on older versions of MC?

**Comment by Lorias-Jak** [comment]
Hey, sure I can explain a little further ^^

The current problem with the mute part is that Velocity kicks you as soon as you try to cancel the event. You can still listen to it, as soon as you try to prevent or change the event result on the proxy side, you will be kicked due to protocol errors. 

- We could try to make the whole thing possible limited to a velocity version until this signed-chat change was implemented. 
- Or I could find a way to work around it and get the signed information away from the chat message. I believe there is already a plugin that does this, but I haven't had the time to look. 

If you give me a few days, I'll see if I can find something and get back to you or make a new push and add the stuff I took down!

**Comment by Lorias-Jak** [comment]
Okay short search has revealed that there is a plugin, which already handles the whole Signed-Messages thing. Maybe it is also possible on newer versions to have a functional proxy side chat-mute. The whole thing would then mean a dependency on the newer versions. I do not know how you like something like that

https://hangar.papermc.io/4drian3d/UnSignedVelocity

An answer would be great, before i countinue coding ^^ 
Thanks anyways for your feedback!

**Comment by Lorias-Jak** [comment]
Okay, long story short, it all works on Velocity now and I added queries to check the conditions. I had to change from UnSignedVelocity to SignedVelocity which is the newer and bug free version. 

- BanManager is up to Velocity version 3.1.2 - 140 can be used without problems. No dependency is needed. 
- Between versions 3.1.2-141 and 3.2.0-234 the mute function does not work at all.
- As of version 3.2.0-235, you need SignedVelocity on both the proxy and the respective subserver. 
( https://modrinth.com/plugin/signedvelocity/versions#all-versions )

I think this is the best way, I tested it and everything should work so far, at least for me everything works. I pack the system on the weekend on my server and drive a stress test, whether really everything goes and with us errors occur. If none occur, I will write again what about it. 
I am still open for comments and if the whole merged, I am always open to be pinged if errors should occur. 
If you still have questions, please just ask!

**Comment by Lorias-Jak** [comment]
I tested the plugin over 2 days and here's what I noticed:
- WebEnhancer also needs a velocity update if BMVelocity is used.
- ChatPlugins ignore the proxy-side mute, you would have to develop a Bukkit, Paper, etc. side solution for this, which communicates with the proxy (PluginMessaging)
- Reports are not possible on the proxy side
- Bans, kicks, notes, etc. work as intended

Recommendation: 
From my point of view the whole thing is ready to use with the limitation that mutes unfortunately do not come to effect due to ChatPlugins. You would have to split BanManager into individual modules and make sure that the mutes are server-side so that the chat plugins don't overwrite the whole thing. I can imagine that it is possible to capture and enforce mutes via PluginMessaging. Also I would integrate in something then also the report function, so that this is also usable if BanManager is on the proxy.

**Comment by BrycensRanch** [comment]
DOPE

**Pull request merged**
